openapi: 3.0.1
info:
  title: Product Service API
  description: API documentation for Collaboration Supply Chain Platform Product Service
  version: v1.0

servers:
  - url: http://localhost:3002
    description: Generated server url

paths:
  /api/v1/product/{id}:
    get:
      tags:
        - product-controller
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'

    put:
      tags:
        - product-controller
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string

    delete:
      tags:
        - product-controller
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string

  /api/v1/product:
    get:
      tags:
        - product-controller
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags:
        - product-controller
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string

  /api/v1/product/supplier/{supplierId}:
    get:
      tags:
        - product-controller
      operationId: getProductsBySupplier
      parameters:
        - name: supplierId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /api/v1/product/shortage:
    get:
      tags:
        - product-controller
      operationId: getProductsInShortage
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /api/v1/product/category/{category}:
    get:
      tags:
        - product-controller
      operationId: getProductsByCategory
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        quantity:
          type: integer
          format: int32
        price:
          type: number
          format: double
        supplierId:
          type: string
        tags:
          type: array
          items:
            type: string
        shortageThreshold:
          type: integer
          format: int32
        listedAt:
          type: string
          format: date-time
        shortage:
          type: boolean
